<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const URL = 'https://api.thecatapi.com/v1/images/search'

    axios({
      method: 'GET',
      url: URL
    })
      .then((response) => {
        console.log(response)
        console.log(response.data)
      })
      .catch((error) => {
        console.log(error)
      })  // 해당 catch는 catch 위에 then에 대해서만 에러를 표시할 수 있다.
          // catch 아래에 있는 then에 대해서는 확인 불가능
    console.log('야옹야옹')



  </script>
</body>

</html>
